zenstackhq/zenstack

- packages/schema/package.json
- packages/schema/src/language-server/zmodel-linker.ts
- pnpm-lock.yaml
Otherwise VSCode extension may break
> fix: proceed with linking even if zmodel contains parsing error

- packages/testtools/src/schema.ts
> fix(#329): normalize testtools workspace root path for win32

- packages/schema/package.json
- packages/schema/src/cli/config.ts
- packages/schema/src/cli/index.ts
- packages/schema/src/cli/plugin-runner.ts
- packages/schema/src/plugins/prisma/index.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/tests/cli/command.test.ts
- packages/schema/tests/cli/config.test.ts
- packages/schema/tests/generator/prisma-generator.test.ts
- packages/sdk/src/types.ts
- pnpm-lock.yaml
Use "--config" to pass in a JSON config file. By default it loads from "zenstack.config.json" if it exists.
Current config options:
- guardFieldName: custom mapping name for "zenstack_guard"
- transactionFieldName: custom mapping name for "zenstack_transaction"
> feat: add CLI config file support

- packages/schema/src/cli/config.ts
- packages/schema/src/cli/index.ts
- packages/schema/tests/cli/config.test.ts
- packages/testtools/src/schema.ts
fixes #343 
- slightly more granular error reporting for config file issues
- slightly better test coverage
> fix: better cli reporting of missing/invalid config file

- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- packages/language/syntaxes/zmodel.tmLanguage.json
- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/src/language-server/validator/expression-validator.ts
- packages/schema/src/language-server/validator/utils.ts
- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/tests/generator/prisma-generator.test.ts
- packages/schema/tests/schema/parser.test.ts
- packages/schema/tests/schema/validation/datamodel-validation.test.ts
- Directly map to Prisma's `Unsupported` type
- Disallow using unsupported field in expressions
> feat: support "Unsupported" field type

- packages/schema/src/language-server/validator/schema-validator.ts
- packages/schema/src/language-server/zmodel-definition.ts
- packages/schema/src/language-server/zmodel-module.ts
- packages/schema/src/utils/ast-utils.ts
- packages/schema/tests/schema/validation/schema-validation.test.ts
- show an error if cannot find the imported model file 
- support Go To Definition for valid import statement
> feat: import statment validation

- package.json
- packages/language/package.json
- packages/next/package.json
- packages/plugins/openapi/package.json
- packages/plugins/react/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/schema/package.json
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
- packages/schema/src/plugins/access-policy/typescript-expression-transformer.ts
- packages/schema/src/plugins/access-policy/utils.ts
- packages/schema/src/utils/ast-utils.ts
- packages/schema/tests/plugins/policy.test.ts
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
- packages/testtools/src/schema.ts
- tests/integration/test-run/package-lock.json
- policy generation: let policy function return a boolean value if no rule depends on model fields
- during post-read check, short-circuit if policy function returns boolean and there's not additional zod schema check work to do
> fix: short-circuit post-read check when policy rules don't depend on model fields

- packages/schema/src/language-server/utils.ts
- packages/schema/src/language-server/validator/datamodel-validator.ts
- tests/integration/tests/regression/issues.test.ts
> fix: wrong validation error when relation field is marked @id instead of @unique

- package.json
- packages/language/package.json
- packages/next/package.json
- packages/plugins/openapi/package.json
- packages/plugins/react/package.json
- packages/plugins/swr/package.json
- packages/plugins/swr/res/helper.ts
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/constants.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/utils.ts
- packages/schema/package.json
- packages/sdk/package.json
- packages/sdk/src/constants.ts
- packages/server/package.json
- packages/server/src/api/utils.ts
- packages/testtools/package.json
- pnpm-lock.yaml
- tests/integration/test-run/package-lock.json
- refactor package inter-dependencies
- disable eslint for generated hooks
> merge dev to main

- package.json
- packages/language/package.json
- packages/next/package.json
- packages/plugins/openapi/package.json
- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest.baseline.yaml
- packages/plugins/react/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/utils.ts
- packages/schema/package.json
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/tests/generator/prisma-generator.test.ts
- packages/sdk/package.json
- packages/server/package.json
- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
- packages/testtools/package.json
- tests/integration/test-run/package-lock.json
- generate aux fields when a model is related by another model with policies
- avoid throwing then a model doesn't have id field
- add Prisma error code to error response if available
> fix: open-api issues

- packages/runtime/src/enhancements/utils.ts
https://github.com/zenstackhq/zenstack/issues/449
> fix: avoid return loaded prisma if undefined

- packages/schema/src/plugins/plugin-utils.ts
> fix: generate .zenstack with the same level of @zenstackhq

- packages/schema/src/res/stdlib.zmodel
- packages/schema/tests/schema/validation/attribute-validation.test.ts
> fix: add missing parameters to `@db.Decimal`

- packages/schema/src/plugins/access-policy/typescript-expression-transformer.ts
- packages/schema/tests/generator/expression-writer.test.ts
- tests/integration/tests/e2e/mist-function-coverage.test.ts
> feat: support `now()` function in policy rules

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
> fix: rest-api, wrong links generated for to-one relationship

- packages/plugins/trpc/src/config.ts
- packages/plugins/trpc/src/generator.ts
- packages/plugins/trpc/tests/trpc.test.ts
> feat: trpc plugin, add "generateModelActions" option to control what operations to generate

- packages/schema/src/utils/ast-utils.ts
- packages/schema/tests/generator/prisma-generator.test.ts
> fix:Inherited fields from abstract model should be on the top

- packages/plugins/tanstack-query/tests/plugin.test.ts
- packages/plugins/trpc/package.json
- packages/plugins/trpc/res/client/next.ts
- packages/plugins/trpc/res/client/react.ts
- packages/plugins/trpc/res/client/utils.ts
- packages/plugins/trpc/src/generator.ts
- packages/plugins/trpc/src/helpers.ts
- packages/plugins/trpc/tests/trpc.test.ts
- pnpm-lock.yaml
> feat: trpc plugin, generate client helpers to provide prisima-like typing

- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/tests/schema/parser.test.ts
> fix: resolve to the correct enum in field attribute when there's ambiguity

- packages/plugins/react/src/generator/react-query.ts
- packages/plugins/react/src/generator/swr.ts
- packages/plugins/swr/src/generator.ts
- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/trpc/src/generator.ts
- packages/plugins/trpc/src/helpers.ts
- packages/plugins/trpc/src/zod/generator.ts
- packages/plugins/trpc/src/zod/transformer.ts
- packages/plugins/trpc/src/zod/types.ts
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/schema/src/plugins/zod/types.ts
- packages/schema/tests/cli/plugins.test.ts
- packages/schema/tests/plugins/policy.test.ts
- packages/sdk/src/index.ts
- packages/sdk/src/prisma.ts
> fix: support for custom prisma client output path

- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- packages/schema/tests/schema/parser.test.ts
change Boolean from terminal to rule
> fix: Validation errors when using true or false as prefix of id

- package.json
- packages/plugins/swr/res/helper.ts
- packages/plugins/swr/src/generator.ts
- packages/plugins/tanstack-query/res/react/helper.ts
- packages/plugins/tanstack-query/res/shared.ts
- packages/plugins/tanstack-query/res/svelte/helper.ts
- packages/plugins/tanstack-query/src/generator.ts
> feat: allow to use custom fetch with generated hooks

- packages/schema/src/plugins/prisma/schema-generator.ts
> fix: add "interactiveTransactions" preview features for lower version of Prisma

- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- packages/language/syntaxes/zmodel.tmLanguage.json
- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/src/plugins/prisma/prisma-builder.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/tests/generator/prisma-generator.test.ts
- packages/schema/tests/schema/parser.test.ts
- packages/schema/tests/schema/trigger-dev.test.ts
- packages/schema/tests/schema/trigger-dev.zmodel
- packages/schema/tests/schema/validation/datamodel-validation.test.ts
- packages/sdk/src/utils.ts
- tests/integration/tests/with-policy/multi-id-fields.test.ts
- tests/integration/tests/with-policy/unique-as-id.test.ts
- tests/integration/tests/with-policy/view.test.ts
> feat: support Prisma view

- packages/sdk/src/prisma.ts
Normalize Prisma import relative path
fix #582
> fix: policy generator fails on Windows for custom output path

- packages/runtime/package.json
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/index.ts
- packages/runtime/src/version.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/src/telemetry.ts
- packages/sdk/src/prisma.ts
- packages/testtools/src/package.template.json
- pnpm-lock.yaml
- tests/integration/test-run/package.json
- tests/integration/tests/enhancements/with-policy/deep-nested.test.ts
- tests/integration/tests/frameworks/nextjs/test-project/package.json
- tests/integration/tests/frameworks/trpc/test-project/package.json
Use the "extendedWhereUnique" preview feature to avoid post-read policy check
> refactor: perf improvement for nullable to-one nested read

- packages/runtime/src/constants.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/index.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/integration/tests/enhancements/with-policy/deep-nested.test.ts
- tests/integration/tests/enhancements/with-policy/nested-to-one.test.ts
- tests/integration/tests/enhancements/with-policy/view.test.ts
- Require minimum Prisma version 4.8.0
- Hoist non-nullable to-one read filter to toplevel
> refactor: avoid post-read checking for non-nullable to-one relation

- packages/runtime/src/enhancements/policy/index.ts
- packages/runtime/src/enhancements/utils.ts
- tests/integration/tests/enhancements/with-policy/auth.test.ts
- tests/integration/tests/enhancements/with-policy/multi-id-fields.test.ts
> fix: issue 599, throw error if the given user context doesn't contain full id fields

- packages/runtime/src/enhancements/policy/policy-utils.ts
- pnpm-lock.yaml
- tests/integration/tests/regression/issues.test.ts
> fix: conditions hoisted from nested read overwrites toplevel where conditions

- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/types.ts
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
> fix: typing of policy definition

- packages/plugins/openapi/src/rpc-generator.ts
- packages/plugins/openapi/tests/openapi-rpc.test.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/schema/src/plugins/zod/types.ts
- packages/schema/src/res/stdlib.zmodel
- packages/sdk/src/utils.ts
- pnpm-lock.yaml
- tests/integration/tests/plugins/zod.test.ts
> fix: zod and openapi generation error when "fullTextSearch" is enabled

- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/src/language-server/validator/utils.ts
- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/src/plugins/access-policy/expression-writer.ts
- packages/schema/src/plugins/model-meta/index.ts
- packages/schema/src/plugins/prisma/prisma-builder.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/src/plugins/prisma/zmodel-code-generator.ts
- packages/schema/src/utils/typescript-expression-transformer.ts
- packages/schema/tests/schema/parser.test.ts
- pnpm-lock.yaml
- tests/integration/tests/regression/issue-646.test.ts
Parse number literal into string value to preserve its original representation.
Fixes #646
> fix: number literal precision issue

- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- packages/schema/src/plugins/prisma/prisma-builder.ts
- packages/schema/tests/schema/parser.test.ts
- packages/testtools/src/schema.ts
- tests/integration/tests/regression/issue-416.test.ts
> fix: support for string escaping in ZModel

- packages/server/src/fastify/plugin.ts
Adresses #684 
Returning the replying, fixing some use case such as utilizing async fastify hook.
(see https://fastify.dev/docs/latest/Reference/Routes/#async-await)
> fix: fastify plugin correctly returning the reply #684

- .github/ISSUE_TEMPLATE/feature_request.md
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/server/src/api/rpc/index.ts
- tests/integration/tests/plugins/zod.test.ts
> feat: add switch to zod plugin to control whether unchecked input types are generated

- packages/schema/src/cli/actions/generate.ts
- packages/schema/src/cli/actions/index.ts
- packages/schema/src/cli/actions/info.ts
- packages/schema/src/cli/actions/init.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/cli/index.ts
- pnpm-lock.yaml
- warn when multiple versions of zenstack packages are detected
- check for new version
- refactor CLI actions
Fixes #547 #175
> feat: CLI improvements

- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/types.ts
- packages/schema/src/plugins/model-meta/index.ts
- tests/integration/tests/regression/issue-714.test.ts
> fix: wrong payload injected for nested create in update

- packages/language/package.json
The `"contributes"` block allows the `language` package to be imported by text editors and IDEs as a TextMate Bundle, providing rudimentary ZenStack support to unsupported IDEs.
> Add `"contributes"` block

- packages/plugins/openapi/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/schema/package.json
- packages/server/package.json
- packages/testtools/src/package.template.json
- pnpm-lock.yaml
- tests/integration/test-run/package.json
- tests/integration/tests/frameworks/nextjs/test-project/package.json
- tests/integration/tests/frameworks/trpc/test-project/package.json
Of note, Zod < `3.22.3` is [vulnerable to ReDOS](https://github.com/advisories/GHSA-m95q-7qp3-xv42).
Would recommend updating the dependency ASAP.
Zod's [changelog](https://github.com/colinhacks/zod/releases) doesn't obviously reflect any breaking API changes from `3.21.1` -> `3.22.4`, and I'm pretty sure Zod adheres to [SemVer](https://semver.org/) so the version numbers agree with this.
> Update `zod` dependency to latest (`v3.22.4`)

- packages/plugins/trpc/src/generator.ts
- packages/plugins/trpc/tests/trpc.test.ts
- packages/schema/src/cli/plugin-runner.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/sdk/src/utils.ts
- tests/integration/tests/plugins/zod.test.ts
> feat: support configuring what models to include for zod and trpc plugins

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest-type-coverage.baseline.yaml
- packages/plugins/openapi/tests/baseline/rest.baseline.yaml
- packages/plugins/openapi/tests/baseline/rpc.baseline.yaml
- packages/plugins/openapi/tests/openapi-restful.test.ts
- packages/plugins/openapi/tests/openapi-rpc.test.ts
> fix: openapi - do not generate "id" field in create input if the field has default value

- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/tests/schema/validation/attribute-validation.test.ts
- tests/integration/tests/regression/issue-756.test.ts
> fix: resolve member access expr only in the context of operand type

- packages/runtime/src/enhancements/policy/policy-utils.ts
- tests/integration/tests/cli/plugins.test.ts
- tests/integration/tests/enhancements/with-policy/nested-to-many.test.ts
- tests/integration/tests/regression/issue-764.test.ts
> fix: incorrect policy injection for nested to-one relation inside a to-many parent

- packages/runtime/src/enhancements/nested-write-visitor.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- tests/integration/tests/regression/issue-765.test.ts
> fix: deal with payload field value with undefined

- packages/schema/src/language-server/zmodel-module.ts
- packages/schema/src/language-server/zmodel-semantic.ts
- packages/schema/syntaxes/zmodel.tmLanguage.json
> feat: Make ZModel color schema looks cool and consistent

- packages/runtime/src/cross/model-meta.ts
- packages/runtime/src/enhancements/policy/index.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/language-server/validator/schema-validator.ts
- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
- packages/schema/tests/schema/validation/schema-validation.test.ts
- packages/sdk/src/model-meta-generator.ts
- packages/sdk/src/utils.ts
- tests/integration/tests/enhancements/with-policy/auth.test.ts
> feat: runtime support for custom `@@auth` model

- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
- tests/integration/tests/enhancements/with-policy/field-level-policy.test.ts
> fix: when field policy only has deny rule, access should be allowed when the rule doesn't satisfy

- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/tanstack-query/src/runtime-v5/react.ts
- packages/plugins/tanstack-query/src/runtime-v5/svelte.ts
- packages/plugins/tanstack-query/src/runtime/common.ts
- packages/plugins/tanstack-query/src/runtime/react.ts
- packages/plugins/tanstack-query/src/runtime/svelte.ts
- packages/plugins/tanstack-query/src/runtime/vue.ts
- packages/plugins/tanstack-query/tests/react-hooks-v5.test.tsx
- packages/plugins/tanstack-query/tests/react-hooks.test.tsx
- packages/runtime/package.json
- packages/runtime/src/cross/index.ts
- packages/runtime/src/cross/model-data-visitor.ts
- packages/runtime/src/cross/model-meta.ts
- packages/runtime/src/cross/mutator.ts
- packages/runtime/src/cross/utils.ts
- packages/runtime/src/enhancements/omit.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/index.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/utils.ts
- packages/sdk/src/model-meta-generator.ts
- packages/server/src/api/rest/index.ts
- pnpm-lock.yaml
> feat: automatic optimistic update for tanstack hooks

- packages/schema/src/plugins/prisma/schema-generator.ts
> fix: zenstack generate fails when path contains space

- packages/schema/src/language-server/validator/expression-validator.ts
- packages/schema/src/language-server/zmodel-linker.ts
- tests/integration/tests/regression/issue-804.test.ts
> fix: stricter binary operation operand type compatibility check

- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/version.ts
- packages/schema/src/language-server/validator/attribute-application-validator.ts
- packages/schema/tests/schema/validation/attribute-validation.test.ts
- tests/integration/tests/enhancements/with-policy/field-level-policy.test.ts
- Disallow field-level policies on relation fields (should be put on foreign keys)
- Translate connect/disconnect/set relation update to foreign key field-level policy check
Fixes #819
> fix: handle foreign key field-level access check during relation update

- packages/schema/src/cli/actions/repl.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/cli/plugin-runner.ts
> fix: repl in pnpm environment, improve relative path module loading

- packages/schema/src/cli/actions/format.ts
- packages/schema/src/cli/actions/index.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/cli/index.ts
- packages/schema/tests/schema/formatter.test.ts
- tests/integration/tests/cli/format.test.ts
> feat:Support ZModel format command in CLI

- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/utils/schema-gen.ts
> fix: generate foreign key field in zod schemas

- packages/schema/src/cli/actions/format.ts
- packages/schema/src/cli/actions/generate.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/cli/index.ts
> feat: allow specifying zmodel location in package.json

- packages/runtime/src/constants.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/types.ts
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
- packages/schema/src/res/stdlib.zmodel
- tests/integration/jest.config.ts
- tests/integration/tests/enhancements/with-policy/connect-disconnect.test.ts
- tests/integration/tests/enhancements/with-policy/field-level-policy.test.ts
- tests/integration/tests/enhancements/with-policy/relation-one-to-many-filter.test.ts
> feat: field-level policy override

- packages/schema/src/language-server/zmodel-code-action.ts
It happens when the opposite model has no fields defined: 
```prisma
abstract model Base {
id Int @id @default(autoincrement())
}
model User {
id Int @id @default(autoincrement())
FieldTemplate FieldTemplate[]
}
model FieldTemplate extends Base {
}
```
Use the end position of the opposite model as the target insertion place
> fix: VsCode error textDocument/codeAction failed

- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/utils/schema-gen.ts
- tests/integration/tests/regression/issue-864.test.ts
- tests/integration/tests/regression/issue-886.test.ts
> fix: support default values in generated zod schemas

- packages/schema/src/language-server/validator/expression-validator.ts
- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/src/utils/ast-utils.ts
- packages/schema/tests/schema/validation/attribute-validation.test.ts
> fix: Show validation error for the field comparison not in the same model

- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/tests/schema/zmodel-generator.test.ts
- tests/integration/tests/regression/issue-925.test.ts
> fix: reference resolution issue inside collection predicate expressions

- packages/schema/src/res/stdlib.zmodel
- packages/schema/tests/schema/validation/attribute-validation.test.ts
support `@nanoid`
- handle with or without `length` argument
- add test
Prisma ref: https://github.com/prisma/prisma-engines/pull/3556
Fixes: https://github.com/zenstackhq/zenstack/issues/923
> Support @nanoid

- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/tanstack-query/src/runtime-v5/svelte.ts
- packages/plugins/tanstack-query/src/runtime/svelte.ts
> fix: typing generated for options parameter in the hooks method

- packages/schema/src/telemetry.ts
- packages/schema/src/utils/machine-id-utils.ts
- pnpm-lock.yaml
> fix: remove warning in vercel environment

- package.json
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/cross/model-meta.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/schema/package.json
- packages/sdk/package.json
- packages/sdk/src/model-meta-generator.ts
- packages/server/package.json
- packages/testtools/package.json
- tests/integration/tests/enhancements/with-policy/deep-nested.test.ts
- tests/integration/tests/regression/issue-961.test.ts
> fix: issue 961, incorrect policy injection for nested `updateMany`

- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/tanstack-query/src/runtime-v5/react.ts
- packages/plugins/tanstack-query/src/runtime-v5/svelte.ts
- packages/plugins/tanstack-query/src/runtime/react.ts
- packages/plugins/tanstack-query/src/runtime/svelte.ts
- packages/plugins/tanstack-query/src/runtime/vue.ts
- packages/plugins/tanstack-query/tests/plugin.test.ts
> fix: tanstack-query, fix the incorrect query typing when user provides a custom selector

- package.json
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/index.ts
- packages/schema/package.json
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
- tests/integration/tests/cli/generate.test.ts
> feat: make parameters of transactions configurable

- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/tests/schema/validation/attribute-validation.test.ts
- packages/schema/tests/schema/validation/datamodel-validation.test.ts
- tests/integration/tests/regression/issue-965.test.ts
> fix: incorrect validation errors for abstract models with validation rules

- packages/schema/src/language-server/zmodel-linker.ts
- tests/integration/tests/regression/issue-971.test.ts
> fix: Zmodel linker doesn't recursively visit base types when building resolution scopes

- packages/runtime/src/enhancements/omit.ts
- tests/integration/tests/enhancements/with-omit/with-omit.test.ts
- tests/integration/tests/regression/issue-992.test.ts
> fix: @omit doesn't remove fields inside to-many relation

- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/tanstack-query/src/runtime-v5/react.ts
> fix: generate suspense queries in tanstack-query plugin

- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/tests/schema/stdlib.test.ts
- packages/schema/tests/schema/validation/datamodel-validation.test.ts
- packages/schema/tests/schema/validation/datasource-validation.test.ts
- packages/schema/tests/utils.ts
This PR fixes an issue where enum types were being marked as invalid for id fields. 
Also, I improved `SchemaLoadingError`, so that it shows the source of the error in jest, rather than inside the utility function. In addition, you can pass it an array of errors rather than strings. (It will still take those too!)
I also created the `safelyLoadModel` utility function, which uses `Promise.allSettled` to get a result that you can use `toMatchObject`, which allows for easier pattern-matching of complex responses.
For `packages/schema/tests/schema/validation/datamodel-validation.test.ts`, I broke up the expect calls into their own tests for easy identification of what went wrong when something breaks. They will of course show up as individual tests in the errors.
> Allows enum types for id fields

- packages/plugins/trpc/tests/projects/t3-trpc-v10/package.json
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/Post.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/User.router.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/utils/ast-utils.ts
- tests/integration/tests/regression/issue-1210.test.ts
> fix: $containerIndex is not updated after merging imported declarations

- packages/runtime/src/enhancements/create-enhancement.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/query-utils.ts
- tests/integration/tests/enhancements/with-policy/field-validation.test.ts
> refactor: make data validation a separate enhancement kind

- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/Post.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/User.router.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/schema/src/plugins/access-policy/expression-writer.ts
- packages/schema/src/plugins/access-policy/policy-guard-generator.ts
- packages/schema/src/utils/typescript-expression-transformer.ts
- tests/integration/tests/regression/issue-1235.test.ts
> fix: post-update rule for id field is not effective if id is updated

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/enhancer/index.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- Use `@zenstackhq/runtime/models` to import logical prisma client types
- Except for zod plugin, when generating into default location, still use ".zenstack/models" to avoid cyclic dependencies
- Only run prisma client generator when generating for logical schema
> fix: compatibility with pnpm monorepo

- packages/runtime/package.json
- packages/runtime/src/enhancements/policy/constraint-solver.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/logic-solver.d.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/types.ts
- packages/runtime/src/types.ts
- packages/schema/src/plugins/enhancer/enhance/checker-type-generator.ts
- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/enhancer/policy/constraint-transformer.ts
- packages/schema/src/plugins/enhancer/policy/policy-guard-generator.ts
- packages/sdk/src/utils.ts
- packages/server/src/api/rpc/index.ts
- packages/server/tests/api/rpc.test.ts
- packages/testtools/src/schema.ts
- pnpm-lock.yaml
- tests/integration/tests/enhancements/with-policy/checker.test.ts
- tests/regression/tests/issue-961.test.ts
> feat: implementing permission checker

- packages/runtime/src/enhancements/delegate.ts
- tests/regression/tests/issue-1410.test.ts
> fix(delegate): fields from delegate models used in logical groups inside filter are not translated

- package.json
- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- pnpm-lock.yaml
- tests/integration/tests/e2e/type-coverage.test.ts
> fix(zmodel): allow type names to be used as declaration names

- packages/schema/src/plugins/zod/utils/schema-gen.ts
- packages/schema/src/utils/pkg-utils.ts
- tests/regression/tests/issue-1378.test.ts
> fix(zod): generate optional field as `z.optional()` rather than `z.nullish()` to be consistent with Prisma's typing

- packages/schema/src/language-server/utils.ts
- packages/schema/src/language-server/zmodel-linker.ts
- packages/schema/src/language-server/zmodel-scope.ts
- packages/schema/src/utils/ast-utils.ts
- tests/regression/tests/issue-1388.test.ts
> fix(zmodel): resolve `auth()` from all loaded and reachable documents

- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/schema/src/language-server/validator/expression-validator.ts
- packages/schema/tests/schema/validation/attribute-validation.test.ts
- tests/regression/tests/issue-1427.test.ts
> fix: relation fields are included even if they are set `false` in select clause

- packages/plugins/openapi/src/rpc-generator.ts
- packages/plugins/swr/src/generator.ts
- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/trpc/src/generator.ts
- packages/plugins/trpc/src/helpers.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/schema/src/plugins/zod/types.ts
- packages/sdk/package.json
- packages/sdk/src/dmmf-helpers/include-helpers.ts
- packages/sdk/src/dmmf-helpers/model-helpers.ts
- packages/sdk/src/dmmf-helpers/modelArgs-helpers.ts
- packages/sdk/src/dmmf-helpers/select-helpers.ts
- packages/sdk/src/utils.ts
- packages/testtools/src/schema.ts
- pnpm-lock.yaml
- tests/integration/tests/enhancements/with-policy/prisma-omit.test.ts
- Upgrade `@prisma/internals` and `@prisma/generator-helper` to latest.
- Respect `omit` clause when reading entities.
- Conditionally generate `createMany` based on Prisma version.
> fix: compatibility with Prisma's "omit" feature

- packages/plugins/trpc/src/helpers.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/Post.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/User.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/index.ts
> fix(trpc): temp workaround for Node.js importing from CJS module issue

- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
Fixing bug from https://github.com/zenstackhq/zenstack/pull/1424 that errored if a special name e.g. `DateTime` was used in an Enum name
> allow enum names to be used as declaration names

- packages/runtime/src/enhancements/policy/constraint-solver.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/types.ts
- packages/runtime/src/types.ts
- packages/schema/src/language-server/validator/expression-validator.ts
- packages/schema/src/plugins/enhancer/policy/policy-guard-generator.ts
- packages/schema/src/plugins/enhancer/policy/utils.ts
- packages/schema/tests/schema/validation/attribute-validation.test.ts
- packages/schema/tests/schema/validation/datamodel-validation.test.ts
- packages/sdk/src/typescript-expression-transformer.ts
- tests/integration/tests/enhancements/with-policy/cross-model-field-comparison.test.ts
- tests/integration/tests/enhancements/with-policy/field-level-policy.test.ts
- Generate TS checker functions to evaluate rules in JS runtime
- Make sure fields needed in the checker are selected when reading entities
Only supporting mutation rules (create, update, post-update, delete) because:
1. Evaluating read in JS runtime may result in reading lots of rows and then discard
2. Don't know how to support aggregation without reading all rows
Fixes #1463 #786
> feat: allow comparing fields from different models in mutation policies

- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/proxy.ts
- packages/runtime/src/types.ts
- tests/integration/tests/enhancements/with-policy/create-many-and-return.test.ts
> feat(runtime): support for Prisma 5.14's `createManyAndReturn`

- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/regression/tests/issue-1466.test.ts
Fixes #1466 
- Shorten long names with a threshold
- Fixed issues with missing `@unique` attribute in generated aux fk fields
> fix: polymorphic logical Prisma schema has identifiers with too long names

- packages/schema/src/plugins/zod/utils/schema-gen.ts
- tests/integration/tests/plugins/zod.test.ts
Zod schemas fail to generate when using a `BigInt` type and a `@default` field, since the generated Zod `.schema.ts` files use a `number` literal instead of a `BigInt` for the default value.
Currently, a ZenStack schema like:
```zenstack
model Post {
viewMilliseconds BigInt @default(0)
}
```
would get converted to the following, which throws a TypeScript error
```ts
const baseSchema = z.object({
// Argument of type 'number' is not assignable to parameter of type 'bigint'.
viewMilliseconds: z.bigint().default(0)
});
```
Now, it would instead be converted to:
```ts
const baseSchema = z.object({
// we're not using .default(0n) since that syntax only works if
// TypeScript is setup to target ES2020 or later
viewMilliseconds: z.bigint().default(BigInt("0"))
});
```
```console …
```
> fix(zod): support `@default` for `BigInt` values

- packages/runtime/package.json
- packages/runtime/src/enhancements/delegate.ts
- pnpm-lock.yaml
- tests/regression/tests/issue-1487.test.ts
> fix(delegate): avoid merging into object of Decimal, Date, etc.

- packages/runtime/src/enhancements/delegate.ts
- tests/regression/tests/issue-1483.test.ts
> fix(delegate): null reference when reading an optional relation

- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/types.ts
- packages/schema/src/plugins/enhancer/policy/policy-guard-generator.ts
- tests/integration/tests/enhancements/with-policy/relation-one-to-many-filter.test.ts
- tests/integration/tests/enhancements/with-policy/relation-one-to-one-filter.test.ts
- tests/regression/tests/issue-1454.test.ts
> fix(policy): relation filter should respect field-level policies

- packages/schema/src/plugins/enhancer/policy/utils.ts
- tests/integration/tests/enhancements/with-policy/field-level-policy.test.ts
> fix: field-level access is incorrectly rejected when there're no allow rules

- packages/runtime/src/enhancements/delegate.ts
- tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
- tests/regression/tests/issue-1518.test.ts
> fix(delegate): push base-level id assignment to base payload when creating a concrete entity

- packages/runtime/src/enhancements/delegate.ts
- tests/regression/tests/issue-1522.test.ts
> fix(delegate): make sure concrete fields are included when a polymorphic model field is included in deep nesting

- packages/runtime/src/enhancements/delegate.ts
- tests/regression/tests/issue-1520.test.ts
> fix(delegate): make sure nested `createMany` is converted into regular `create`

- packages/sdk/src/model-meta-generator.ts
- tests/regression/tests/issue-1530.test.ts
> fix: incorrect calculation of backlink field for self-relations

- packages/runtime/package.json
- packages/schema/package.json
- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/sdk/package.json
- packages/testtools/src/schema.ts
- pnpm-lock.yaml
- script/test-scaffold.ts
- tests/integration/test-run/package.json
- tests/integration/tests/cli/plugins.test.ts
- tests/integration/tests/enhancements/with-policy/prisma-omit.test.ts
- tests/integration/tests/frameworks/nextjs/test-project/package.json
- tests/integration/tests/frameworks/trpc/test-project/package.json
- tests/regression/tests/issue-925.test.ts
> fix: support for Prisma 5.16.0

- packages/runtime/package.json
- packages/runtime/src/cross/clone.ts
- packages/runtime/src/cross/index.ts
- packages/runtime/src/cross/mutator.ts
- packages/runtime/src/enhancements/default-auth.ts
- packages/runtime/src/enhancements/delegate.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/proxy.ts
- packages/runtime/src/enhancements/query-utils.ts
- packages/runtime/src/enhancements/utils.ts
- pnpm-lock.yaml
- tests/regression/tests/issue-1533.test.ts
> fix(runtime): avoid duplicating non-plain objects

- packages/runtime/src/enhancements/create-enhancement.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- tests/integration/tests/enhancements/with-password/with-password.test.ts
- tests/integration/tests/enhancements/with-policy/field-validation.test.ts
- tests/integration/tests/enhancements/with-policy/postgres.test.ts
- tests/integration/tests/enhancements/with-policy/todo-sample.test.ts
> fix: '@password' attribute doesn't work well with data validation

- packages/schema/package.json
- packages/schema/src/language-server/validator/attribute-application-validator.ts
- packages/schema/src/language-server/validator/function-invocation-validator.ts
- packages/schema/src/plugins/enhancer/policy/expression-writer.ts
- packages/schema/src/plugins/enhancer/policy/policy-guard-generator.ts
- packages/schema/src/plugins/enhancer/policy/utils.ts
- packages/schema/src/res/stdlib.zmodel
- packages/schema/src/utils/ast-utils.ts
- packages/schema/tests/generator/expression-writer.test.ts
- packages/sdk/src/index.ts
- packages/sdk/src/names.ts
- packages/sdk/src/typescript-expression-transformer.ts
- pnpm-lock.yaml
- tests/integration/tests/enhancements/with-policy/relation-check.test.ts
> feat: implement relation check() function in ZModel

- packages/schema/src/plugins/enhancer/enhance/index.ts
- tests/regression/tests/issue-1493.test.ts
> fix: incorrect typing when Prisma client extension is used with logical client

- packages/schema/src/language-server/zmodel-formatter.ts
- tests/integration/tests/cli/format.test.ts
> fix(vscode): language server error when formatting models with `Unsupported` fields

- packages/schema/package.json
- packages/schema/src/cli/actions/generate.ts
- packages/schema/src/cli/actions/info.ts
- packages/schema/src/cli/cli-util.ts
- pnpm-lock.yaml
> fix(cli): set timeout for latest version check and avoid failing the CLI

- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/sdk/src/model-meta-generator.ts
- packages/sdk/src/utils.ts
- tests/regression/tests/issue-1560.test.ts
> fix(delegate): entity create fails when inheriting from a delegate model that extends an abstract model

- packages/plugins/tanstack-query/src/generator.ts
- packages/plugins/tanstack-query/tests/plugin.test.ts
> fix(tanstack): incorrect vue-query options typing for vue-query v5

- packages/server/src/nestjs/zenstack.module.ts
- packages/server/tests/adapter/nestjs.test.ts
Support for receiving the property used to trigger getEnhancedPrisma for the NestJS module. This is in relation to feature request #1537
> feat(nestjs):  Add prop as optional parameter of getEnhancedPrisma #1537

- packages/runtime/src/enhancements/delegate.ts
- tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
- tests/regression/tests/issue-1585.test.ts
> fix: incorrect prisma query executed when count using a where filter involving a polymorphic base field

- packages/runtime/src/enhancements/delegate.ts
- packages/runtime/src/enhancements/policy/handler.ts
- packages/runtime/src/enhancements/proxy.ts
- tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
- tests/regression/tests/issue-1576.test.ts
> fix: `createManyAndReturn` doesn't work  for polymorphic models

- packages/runtime/src/enhancements/policy/policy-utils.ts
- tests/regression/tests/issue-1574.test.ts
> fix(policy): field-level override rules don't work properly with non-optional to-one relations

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- tests/integration/tests/enhancements/with-delegate/plugin-interaction.test.ts
> fix(zod): zod create/update schemas should exclude discriminator fields

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/enhancer/index.ts
- tests/regression/tests/issue-1610.test.ts
> fix: generated zod schemas fail to compile when outputting to a custom dir

- packages/runtime/src/enhancements/default-auth.ts
- tests/regression/tests/issue-1596.test.ts
> fix(runtime): throw PrismaValidationError when `auth()` is used in `@default` without user context

- packages/schema/src/plugins/enhancer/enhance/index.ts
> fix(delegate): remove `createMany` from delegate input types

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
> fix(api): support filtering with comma-separated values in rest handler

- packages/schema/src/plugins/zod/generator.ts
- tests/integration/tests/enhancements/with-policy/field-validation.test.ts
- tests/regression/tests/issue-1563.test.ts
> fix(zod): don't include @@validate rules when generating schema for validating update input

- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/regression/tests/issue-1551.test.ts
> fix(delegate): generated fk fields shouldn't inherit `@map` attribute from its origin

- packages/runtime/jest.config.ts
- packages/runtime/src/enhancements/policy/policy-utils.ts
- packages/runtime/src/enhancements/utils.ts
- packages/runtime/tests/policy/reduction.test.ts
- tests/regression/tests/issue-1627.test.ts
Prisma issue: prisma/prisma#21856
Fixes #1627
> fix(runtime): improved query reduction to workaround Prisma issue prisma/prisma#21856

- packages/schema/src/cli/actions/check.ts
- packages/schema/src/cli/actions/index.ts
- packages/schema/src/cli/cli-util.ts
- packages/schema/src/cli/index.ts
> feat(cli): new "check" command for validating ZModel

- packages/runtime/src/enhancements/policy/policy-utils.ts
- tests/integration/tests/enhancements/with-policy/create-many-and-return.test.ts
- tests/regression/tests/issue-1644.test.ts
> fix: field-level policy should filter out records when the field used for filtering is not allowed to read

- packages/runtime/src/enhancements/delegate.ts
- tests/regression/tests/issue-1645.test.ts
> fix(delegate): delegate models returned in nested results don't include base fields

- packages/schema/src/plugins/enhancer/policy/expression-writer.ts
- tests/regression/tests/issue-1642.test.ts
> fix: `check` attribute function shouldn't delegate "postUpdate" rules

- packages/schema/src/plugins/enhancer/policy/expression-writer.ts
- tests/integration/tests/enhancements/with-policy/post-update.test.ts
- tests/regression/tests/issue-1648.test.ts
> fix: incorrect policy injection for post-update rules with deep member access

- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/runtime/package.json
- packages/runtime/src/browser/serialization.ts
- pnpm-lock.yaml
> refactor: replace decimal.js with decimal.js-light for smaller footprint

- packages/sdk/src/model-meta-generator.ts
- tests/integration/tests/enhancements/with-delegate/policy-interaction.test.ts
- tests/regression/tests/issue-1674.test.ts
> fix(delegate): update with "connect" is not properly rejected for polymorphic models

- packages/schema/src/cli/actions/generate.ts
- packages/schema/src/cli/index.ts
- packages/schema/src/cli/plugin-runner.ts
- tests/integration/tests/cli/generate.test.ts
> feat(cli): allow to include/exclude plugins when generate

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/plugin-utils.ts
- packages/testtools/src/schema.ts
- tests/integration/tests/plugins/zod.test.ts
- tests/regression/tests/issue-1667.test.ts
> fix(cli): enhancer code fails to compile when generated into a custom folder

- packages/runtime/src/enhancements/node/delegate.ts
- tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
- tests/regression/tests/issue-1698.test.ts
> fix(delegate): concrete model fields are not properly included if queried from a nested context from a parent concrete model

- packages/schema/src/plugins/zod/generator.ts
- tests/regression/tests/issue-1693.test.ts
> fix(zod): generated schemas fail to compile when a delegate discrimin ator field has default value

- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- tests/integration/tests/plugins/zod.test.ts
> feat: non-strict mode for zod plugin

- packages/runtime/package.json
- packages/runtime/src/enhancements/node/delegate.ts
- packages/runtime/src/enhancements/node/omit.ts
- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- packages/runtime/src/enhancements/node/query-utils.ts
- packages/schema/src/res/stdlib.zmodel
- pnpm-lock.yaml
- tests/integration/tests/enhancements/with-delegate/omit-interaction.test.ts
- tests/integration/tests/enhancements/with-delegate/policy-interaction.test.ts
- tests/integration/tests/enhancements/with-delegate/validation.test.ts
- tests/regression/tests/issue-1710.test.ts
> fix(delegate): `@omit` and field-level policies are not enforced when querying with a delegate model

- packages/runtime/src/cross/nested-write-visitor.ts
- packages/runtime/src/cross/types.ts
- packages/runtime/src/enhancements/node/default-auth.ts
- packages/runtime/src/enhancements/node/policy/handler.ts
- tests/integration/tests/enhancements/with-policy/auth.test.ts
- tests/regression/tests/issue-1681.test.ts
> fix: using `auth()` in `@default()` is not effective for `createManyAndReturn`

- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- tests/integration/tests/enhancements/with-password/with-password.test.ts
Again related to https://github.com/prisma/prisma/issues/21856
> fix: field with read-deny can be used to filter due to a prisma bug

- packages/plugins/trpc/src/helpers.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/Post.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v10/src/server/api/routers/generated/routers/User.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v11/src/server/api/routers/generated/routers/Post.router.ts
- packages/plugins/trpc/tests/projects/t3-trpc-v11/src/server/api/routers/generated/routers/User.router.ts
> fix(trpc): make input arg's optionality consistent with Prisma

- package.json
- packages/ide/jetbrains/CHANGELOG.md
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/enhancements/node/delegate.ts
- packages/schema/package.json
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
- tests/regression/tests/issue-1734.test.ts
> fix(delegate): base fields not properly wrapped inside relation layer when injected from policies

- packages/runtime/package.json
- packages/runtime/src/zod-utils.ts
- packages/runtime/tests/zod/smart-union.test.ts
- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/schema/src/plugins/zod/types.ts
- tests/regression/tests/issue-1746.test.ts
> fix(zod): "strip" mode causes create payload fields to be accidentally dropped

- packages/server/package.json
- packages/server/src/hono/handler.ts
- packages/server/src/hono/index.ts
- packages/server/tests/adapter/hono.test.ts
- pnpm-lock.yaml
> feat(server): implementing hono adapter

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
https://github.com/zenstackhq/zenstack/issues/1748
Adds support for the Prisma @@id compound ids to the RESTApiHandler.
[Discord thread](https://discordapp.com/channels/1035538056146595961/1289126659932553236/1289126659932553236)
> RESTApiHandler support compound ids (@@id)

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/enhancer/index.ts
- packages/schema/src/plugins/prisma/index.ts
- packages/sdk/src/index.ts
- packages/sdk/src/path.ts
- packages/sdk/src/prisma.ts
- packages/testtools/src/schema.ts
- tests/regression/tests/issue-1743.test.ts
> fix: generated code fails to compile when prisma's output path overlaps with zenstack

- packages/schema/src/language-server/validator/attribute-application-validator.ts
- tests/regression/tests/issue-1758.test.ts
> fix: generated prisma schema contains error when using "@@unique" with base field

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/server/src/api/rest/index.ts
> fix(delegate): remove `createManyAndReturn` API from delegate model client

- packages/plugins/tanstack-query/package.json
- packages/plugins/tanstack-query/src/runtime/common.ts
- packages/plugins/tanstack-query/tests/plugin.test.ts
- packages/plugins/tanstack-query/tests/react-hooks-v5.test.tsx
- pnpm-lock.yaml
- tests/integration/tests/cli/plugins.test.ts
- tests/integration/tests/enhancements/with-delegate/plugin-interaction.test.ts
> fix(tanstack-query): non-zenstack queries are accidentally visited during optimistic update

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest-3.0.0.baseline.yaml
- packages/plugins/openapi/tests/baseline/rest-3.1.0.baseline.yaml
Fixes #1744 by marking all fields as required for read requests. This allows for more accurate documentation and better type safety for generated clients, until sparse fieldsets are implemented.
> Mark openapi attributes as required for reads

- packages/runtime/src/enhancements/node/delegate.ts
- packages/schema/src/utils/ast-utils.ts
- packages/sdk/src/utils.ts
- tests/integration/tests/enhancements/with-delegate/policy-interaction.test.ts
- tests/regression/tests/issue-1770.test.ts
> fix(delegate): policies inherited from delegate base models are not injected into proper hierarchy

- packages/schema/src/utils/ast-utils.ts
> fix: VSCode extension fails to resolve imports from npm packages in pnpm workspaces

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
- pnpm-lock.yaml
Make id divider in the REST API generator configurable, in case the values contain the default `_` divider.
> Configurable REST API id divider

- packages/server/src/api/rest/index.ts
Decode resourceId so encoded characters (e.g. `:`) can be user as id divider.
> URI decode resourceId 

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
Here are two test cases: For GET requests, we do get the expected empty data array in the relationship response. However, in the response of a PUT request, the data array is missing and the test fails before the included change.
> Include relationships in REST result from creates and updates

- packages/schema/src/plugins/enhancer/enhance/index.ts
- tests/regression/tests/issue-1763.test.ts
> fix(delegate): discriminator fields should be removed from unchecked create/update input types

- packages/server/src/next/app-route-handler.ts
> 🐞 fix (server): support for awaiting next.js 15 params

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest-3.0.0.baseline.yaml
- packages/plugins/openapi/tests/baseline/rest-3.1.0.baseline.yaml
- packages/schema/src/plugins/zod/generator.ts
- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
1. Fixes an issue where adding entities related to entities with compound id (see `makeIdConnect`)
1. Fixes validation of entities with compound id, given that zod schemas expect the attributes separately
1. This is not super elegant, happy to get suggestions on improvements
1. Update openAPI spec generation to match the previous point, making generate clients behave as expected
> Improve working with entities related to entities that uses compound ids

- packages/server/src/api/rest/index.ts
In some cases Prisma doesn’t expect these to be nested under the compound id key. I don't have a full overview of where this is (just the example I hit myself), so I added it just where I can confirm it's needed.
> Fix for filtering by compound id

- packages/schema/src/language-server/zmodel-documentation-provider.ts
- packages/schema/src/language-server/zmodel-module.ts
- packages/schema/src/language-server/zmodel-workspace-manager.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/src/res/starter.zmodel
- packages/schema/tests/generator/prisma-generator.test.ts
> fix(zmodel): prefer to use triple-slash comments as ZModel documentation

- packages/schema/src/utils/ast-utils.ts
- packages/sdk/src/utils.ts
- tests/regression/tests/issue-1786.test.ts
> fix(delegate): delegate model shouldn't inherit `@@index` from an indirect abstract base

- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- packages/runtime/src/enhancements/node/types.ts
- packages/schema/src/plugins/enhancer/policy/constraint-transformer.ts
- tests/integration/tests/enhancements/with-policy/checker.test.ts
> fix: support `check()` policy function call in permission checkers

- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
> fix(delegate): self relation support

- packages/runtime/src/enhancements/node/delegate.ts
- tests/regression/tests/issue-1755.test.ts
> fix(delegate): orderBy with base field doesn't work when the clause is an array

- package.json
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/schema/package.json
- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
- tests/integration/tests/enhancements/json/validation.test.ts
> fix(json): false error when using typed json in multi-file schemas

- packages/language/src/generated/ast.ts
- packages/language/src/generated/grammar.ts
- packages/language/src/zmodel.langium
- packages/schema/src/plugins/enhancer/enhance/model-typedef-generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- tests/integration/tests/enhancements/json/crud.test.ts
- tests/integration/tests/enhancements/json/typing.test.ts
> fix(json): support enums in type declarations

- packages/schema/src/plugins/zod/generator.ts
Generating the zod schemas in a project causes the schemas to be subject to typechecking.
There can be cases where the zod plugin adds an import which doens't end up being used. This raises typechecking errors.
I don't see a reason why these files need to be typechecked.
> fix: ignore file from typechecking

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/src/rpc-generator.ts
- packages/plugins/openapi/tests/baseline/rpc-3.0.0-omit.baseline.yaml
- packages/plugins/openapi/tests/baseline/rpc-3.1.0-omit.baseline.yaml
- packages/plugins/openapi/tests/openapi-rpc.test.ts
> feat(openapi): add plugin option to omit generating input object details for RPC flavor

- packages/schema/src/plugins/plugin-utils.ts
> fix: don't use package name starting with dot

- packages/runtime/src/enhancements/node/delegate.ts
- packages/runtime/src/enhancements/node/query-utils.ts
- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/sdk/src/utils.ts
- tests/regression/tests/issue-1843.test.ts
> fix: make sure both fk and relation fields are optional in create input types

- packages/schema/src/plugins/enhancer/enhance/model-typedef-generator.ts
- tests/regression/tests/issue-1857.test.ts
> fix: allow 'null' values for optional fields in custom types

- packages/sdk/src/code-gen.ts
- tests/integration/tests/enhancements/json/crud.test.ts
- tests/integration/tests/enhancements/json/typing.test.ts
> fix(json): support recursive definitions

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest-3.0.0.baseline.yaml
- packages/plugins/openapi/tests/baseline/rest-3.1.0.baseline.yaml
These attributes are handled as relationships, and as such don't need to be exposed as attributes.
> Don't expose foreign keys as attributes in openAPI spec

- package.json
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/schema/package.json
- packages/schema/src/plugins/prisma/index.ts
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
> fix: zenstack generate warnings in pnpm repo with custom prisma client output dir

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
Adds support for upsert operations in the RESTAPIHandler via metadata. 
We may also want to add documentation about this to the OpenAPI generator.
[Discussion in Discord](https://discord.com/channels/1035538056146595961/1087761218049167380/1299078053653123165)
> feat(server): upsert support for rest api handler

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest-3.0.0.baseline.yaml
- packages/plugins/openapi/tests/baseline/rest-3.1.0.baseline.yaml
- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
When creating a record with a compound id, Prisma expects the parts of the compound id to be passed as attributes. This change reflects that.
> fix(openapi): bugfix for compound id create and update

- packages/schema/src/language-server/validator/expression-validator.ts
- packages/schema/tests/schema/validation/datamodel-validation.test.ts
- tests/regression/tests/issue-1870.test.ts
> fix: support "Unsupported" type of fields in "@@index"

- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/regression/tests/issue-1894.test.ts
> fix(delegate): nested create/connect in delegate model requires reference fields

- packages/plugins/tanstack-query/src/runtime-v5/react.ts
- packages/plugins/tanstack-query/src/runtime-v5/svelte.ts
- packages/plugins/tanstack-query/src/runtime-v5/vue.ts
- packages/plugins/tanstack-query/src/runtime/react.ts
- packages/plugins/tanstack-query/src/runtime/svelte.ts
- packages/plugins/tanstack-query/src/runtime/vue.ts
- packages/plugins/tanstack-query/tests/plugin.test.ts
> feat(tanstack): return query key and pass in abort signal to fetcher

- packages/plugins/openapi/tests/openapi-rpc.test.ts
- packages/schema/src/plugins/enhancer/enhance/index.ts
> fix: make sure the logical DMMF respects `auth()` in `@default`

- package.json
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/schema/package.json
- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
> fix: preserve custom attributes as comments in logical prisma schema

- packages/runtime/src/enhancements/node/create-enhancement.ts
- packages/runtime/src/enhancements/node/encrypted.ts
- packages/runtime/src/types.ts
- packages/schema/src/language-server/validator/attribute-application-validator.ts
- tests/integration/tests/enhancements/with-encrypted/with-encrypted.test.ts
- Rename enhancement from "encrypted" to "encryption" for better consistency
- Use standard logger for warnings
- Throw PrismaClientUnknownError for errors
- Disallow using encrypted fields in access policies
- More tests
Hi @genu , FYI I'm making a couple of minor improvements to the encryption feature.
> feat: improvements to "encryption" enhancement

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/openapi-restful.test.ts
> fix(openapi): type "id" field according to ZModel schema type

- packages/schema/src/language-server/validator/datamodel-validator.ts
- packages/schema/tests/schema/validation/cyclic-inheritance.test.ts
- packages/sdk/src/utils.ts
> fix(zmodel): check cyclic inheritance

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/enhancer/policy/expression-writer.ts
- packages/schema/src/plugins/enhancer/policy/policy-guard-generator.ts
- packages/schema/src/plugins/enhancer/policy/utils.ts
- packages/schema/src/plugins/prisma/schema-generator.ts
- packages/schema/src/utils/ast-utils.ts
- tests/integration/tests/enhancements/with-delegate/policy-interaction.test.ts
- tests/regression/tests/issue-1930.test.ts
> fix(delegate): delegate model's guards are not properly including concrete models

- packages/runtime/src/enhancements/node/delegate.ts
- tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
- tests/regression/tests/issue-1467.test.ts
> fix(delegate): support _count select of base fields

- packages/server/src/api/rest/index.ts
- packages/server/tests/adapter/express.test.ts
- packages/server/tests/adapter/fastify.test.ts
- packages/server/tests/adapter/hono.test.ts
- packages/server/tests/adapter/next.test.ts
- packages/server/tests/adapter/sveltekit.test.ts
- packages/server/tests/api/rest.test.ts
> fix(server): return an object without primary data for delete route

- packages/schema/src/utils/ast-utils.ts
- tests/regression/tests/issue-1647.test.ts
> fix(delegate): don't generate both "@@schema" attributes from base and sub models

- packages/runtime/src/enhancements/node/encryption.ts
- packages/runtime/src/types.ts
- tests/integration/tests/enhancements/with-encrypted/with-encrypted.test.ts
- Persist metadata alongside the encrypted data
- Use key digest to determine the proper key for decryption
> feat(encryption): support providing multiple decryption keys for key rotation

- package.json
- packages/ide/jetbrains/build.gradle.kts
- packages/ide/jetbrains/package.json
- packages/language/package.json
- packages/misc/redwood/package.json
- packages/plugins/openapi/package.json
- packages/plugins/swr/package.json
- packages/plugins/tanstack-query/package.json
- packages/plugins/trpc/package.json
- packages/runtime/package.json
- packages/runtime/src/enhancements/node/policy/handler.ts
- packages/schema/package.json
- packages/sdk/package.json
- packages/server/package.json
- packages/testtools/package.json
- tests/integration/tests/enhancements/with-policy/create-many-and-return.test.ts
- tests/regression/tests/issue-1955.test.ts
> fix(policy): incorrect policy injection for `createManyAndReturn` when the model contains array fields

- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- tests/regression/tests/issue-1978.test.ts
This improves performance by not selecting unnecessary fields (especially relations).
fixes #1978
> fix(policy): only include field selections for evaluating field-level policies if the corresponding fields are selected

- packages/schema/src/plugins/enhancer/enhance/index.ts
- tests/regression/tests/issue-1991.test.ts
> fix(json): incorrect JSON field type generated for inputs

- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/regression/tests/issue-1992.test.ts
> fix(schema): Provide a truncated name for unique constraints with polymorphic fk

- packages/runtime/src/enhancements/node/default-auth.ts
- tests/regression/tests/issue-1989.test.ts
- tests/regression/tests/issue-1997.test.ts
```ts
const result = db.post.create({
data: {
likes: {
createMany: {
data: [{
userId: user.id
}]
}
}
},
include: {
likes: true
}
});
// results in ↓
const result = await db[model].create({
data: {
likes: {
createMany: {
data: [
{
userId: "48a96b75-882e-48bc-92eb-2ec266067b6d",
tenantId: "fa9c2cd6-ae4f-457a-b556-9089f25d67d4"
}
]
}
},
tenant: {
connect: {
id: "fa9c2cd6-ae4f-457a-b556-9089f25d67d4"
}
},
author: {
connect: {
id: "48a96b75-882e-48bc-92eb-2ec266067b6d"
}
}
},
select: {
tenantId: true,
id: true,
likes: {
select: {
tenantId: true,
id: true
}
}
}
})
// Prisma error: Unknown argument `tenantId`. Available options are marked with ?.]
```
> fix: don't set default value in nested writes when set through FK

- packages/schema/src/plugins/zod/generator.ts
- packages/schema/src/plugins/zod/transformer.ts
- packages/sdk/src/model-meta-generator.ts
- packages/sdk/src/utils.ts
- tests/regression/tests/issue-1993.test.ts
> fix(delegate): clean up generated zod schemas for delegate auxiliary fields

- packages/runtime/src/enhancements/node/delegate.ts
- tests/regression/tests/issue-1998.test.ts
> fix(delegate): deleteMany fails when the model has compound id fields

- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- tests/regression/tests/issue-2000.test.ts
> fix(policy): update fails for model using both `@password` and `@@validate`

- packages/runtime/src/enhancements/node/policy/handler.ts
- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- packages/runtime/src/enhancements/node/query-utils.ts
- tests/regression/tests/issue-2007.test.ts
> fix(policy): incorrect field-level permission check for nested create

- packages/runtime/src/enhancements/node/proxy.ts
- tests/regression/tests/issue-2014.test.ts
> fix(runtime): proxy `$extends` for each and every enhancement

- packages/runtime/src/cross/model-meta.ts
- packages/runtime/src/enhancements/node/default-auth.ts
- tests/regression/tests/issue-2019.test.ts
> fix(auth): refix issue #1997

- packages/runtime/src/enhancements/node/proxy.ts
- tests/integration/tests/enhancements/proxy/extension-context.test.ts
Prisma already exposes a `$parent` property in the context, but this will point towards the unenhanced client or transaction object
> feat(runtime): inject enhanced client or tx context so it can be retrieved in extensions

- packages/schema/src/plugins/enhancer/enhance/index.ts
- packages/schema/src/plugins/zod/generator.ts
- tests/regression/tests/issue-2028.test.ts
Fixes #2028
This also silently fixes the enhanced PrismaClient types by updating that code to use `.includes(DELEGATE_AUX_RELATION_PREFIX)` over `.startsWith(DELEGATE_AUX_RELATION_PREFIX)` to search for delegate aux fields.
Unfortunately I couldn't find an easy way to test the PrismaClient types within the existing test infrastructure, so that regression is untested.
> fix(zod): delegate aux fields appearing in WhereUniqueInput schemas

- packages/schema/src/language-server/validator/attribute-application-validator.ts
- packages/schema/src/plugins/zod/transformer.ts
- tests/regression/tests/issue-2039.test.ts
> fix(JSON): @default not working for @JSON types & Typed JSON lists generating invalid Zod schemas

- packages/schema/src/plugins/zod/transformer.ts
- tests/integration/tests/plugins/zod.test.ts
I believe this is just an edge case with Typed JSON fields again, but it did surface what appears to be a legitimate bug in the zod generator code. So I've tidied that section up slightly to fix the issue and improve readability a touch.
Apologies for not catching this with the last PR.
> fix(zod): Required fields with a default value should be optional in Typed JSON cases

- packages/runtime/res/model-meta.d.ts
`export * from` does not re-export default exports, which is how the metadata is exported.
```ts
import metadata from '@zenstackhq/runtime/model-meta`;
//       ^ this contains the correct metadata at runtime but typescript sees it as {}
```
This change fixes the type declaration and correctly aligns the `.d.ts` file with the existing `.js` file
https://github.com/zenstackhq/zenstack/blob/7c379402cab99e1914fb2c0bc28b7a3e037222ed/packages/runtime/res/model-meta.js#L5
> fix(runtime): properly re-export type declarations of model metadata

- packages/schema/src/language-server/validator/function-invocation-validator.ts
- packages/sdk/src/validation.ts
- tests/regression/tests/issue-1984.test.ts
> fix: allow using `currentModel()` and `currentOperation` calls in policy rules

- packages/schema/src/plugins/enhancer/enhance/index.ts
- tests/regression/tests/issue-1994.test.ts
> fix(delegate): resolve from short name back to full name when processing delegate types

- packages/schema/src/plugins/prisma/schema-generator.ts
- tests/regression/tests/issue-2038.test.ts
> fix: incorrect value type when using `@default` with boolean  field from `auth()`

- packages/runtime/src/enhancements/node/delegate.ts
- packages/runtime/src/enhancements/node/policy/handler.ts
- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- packages/runtime/src/enhancements/node/query-utils.ts
- packages/server/src/api/rest/index.ts
- packages/testtools/src/schema.ts
- tests/integration/tests/enhancements/with-policy/unique-as-id.test.ts
- tests/regression/tests/issue-1964.test.ts
- tests/regression/tests/issue-765.test.ts
> fix(policy): revers lookup condition to parent entity is not properly built with compound id fields

- packages/schema/src/plugins/enhancer/enhance/index.ts
- tests/integration/tests/enhancements/json/crud.test.ts
Another JSON edge case!
When the `strictUndefinedChecks` Prisma Preview feature is enabled, `Prisma.skip` is required to be used over `undefined`. The types generated for `@Json` fields misses this typing in cases where the field is optional in the Prisma type, for example within `UpdateInput` types
Note this doesn't allow using `Prisma.skip` on a field within the JSON type, as that doesn't appear to be supported by Prisma.
> Fix(JSON): Allow JSON types to be skipped through Prisma.skip

- packages/schema/src/plugins/enhancer/enhance/index.ts
- tests/regression/tests/issue-2065.test.ts
- tests/regression/tests/issue-foo.test.ts
> fix: make ".zenstack/models" reexport the entire original PrismaClient module

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
> fix(rest): multiple relation id filter values are not properly split

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/tests/baseline/rest-type-coverage-3.0.0.baseline.yaml
- packages/plugins/openapi/tests/baseline/rest-type-coverage-3.1.0.baseline.yaml
- packages/plugins/openapi/tests/openapi-restful.test.ts
> fix(openapi): support spec generation for JSON fields

- packages/plugins/openapi/src/rest-generator.ts
- packages/plugins/openapi/src/rpc-generator.ts
> fix(openapi): ensure output folder created

- packages/server/package.json
- packages/server/src/elysia/handler.ts
- packages/server/src/elysia/index.ts
- packages/server/tests/adapter/elysia.test.ts
- pnpm-lock.yaml
Add [Elysia](https://elysiajs.com/) adapter
> feat: add elysiajs

- packages/schema/src/utils/pkg-utils.ts
- packages/sdk/src/code-gen.ts
- explicitly pass "types": [] to tsconfig to avoid bun compilation errors
- detect bun as package manager when running "zenstack init"
fixes #2124
> fix: bun compatibility

- packages/runtime/src/enhancements/node/policy/policy-utils.ts
- packages/runtime/src/types.ts
- tests/regression/tests/issue-2025.test.ts
> feat(policy): add settings to validate only input data for update

- packages/plugins/openapi/src/rest-generator.ts
- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
implements https://github.com/zenstackhq/zenstack/issues/2178
this PR also adds support for a `prefix` similar to the openapi plugin. note openapi plugin itself still needs to be updated, to also use this model name mapping.
also we did not add any new tests. would appreciate any hints on that.
finally we will of course also be happy to provide documentation for this.
/cc @tobiasbrugger
> feat: add ability to map model names in the URLS/JSON response

- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest.test.ts
this makes it possible to use a natural key even while also using surrogate primary keys
https://www.prisma.io/dataguide/datamodeling/correctness-constraints#the-primary-key
Using the surrogate key might be sensible since it is more compact for foreign keys. Also the tag name might be editable. But inside the API it makes no sense to use the surrogate key.
ie. `/tags/1` makes no sense. `/tags/blue` is the much better developer experience.
In order to make use of this a unique key needs to be defined and referenced in the RESTApiHandler Options:
```
RESTApiHandler({
...
externalIdMapping: {Post: source__post_id},
});
}
```
ie. in the model
```
model Post {
id Int @id @default(autoincrement()) @deny('all', true)
post_id Int
source String
title String?
@@unique([source, post_id], name: …
```
> feat: support natural keys in the API

- packages/plugins/openapi/src/generator-base.ts
Add option "includeOpenApiIgnored" to the OpenAPI-Plugin. If set to true, models tagged with @openapi.ignore are also included in the generated spec.
Our use case is to produce separate API specifications for internal and external audiences. By providing a flag in the OpenAPI plugin, we could easily generate two different spec files - one for internal use and one for customers.
> feat: option to include models tagged with @openapi.ignore in the spec file

- .vscode/launch.json
- packages/server/src/api/rest/index.ts
- packages/server/tests/api/rest-partial.test.ts
implements sparse fieldsets as shown in the specification https://jsonapi.org/format/#fetching-sparse-fieldsets
> Rest api sparse fieldsets

- packages/runtime/src/enhancements/node/delegate.ts
- tests/regression/tests/issue-2246.test.ts
> fix(delegate): issue with filtering concrete relations with fields from base
