zenstackhq/zenstack

packages/schema/package.json
pnpm-lock.yaml

fix: lower vscode engine version requirement

---

docs/vercel.json
package.json
packages/language/package.json
packages/next/package.json
packages/next/src/client.ts
packages/next/src/index.ts
packages/next/src/request-handler.ts
packages/runtime/package.json
packages/runtime/src/client.ts
packages/runtime/src/enhancements/policy/policy-utils.ts
packages/runtime/src/error.ts
packages/runtime/src/index.ts
packages/runtime/src/request.ts
packages/runtime/src/version.ts
packages/schema/package.json
packages/schema/src/cli/index.ts
packages/schema/src/cli/plugin-runner.ts
packages/schema/src/plugins/react-hooks/react-hooks-generator.ts
packages/schema/src/telemetry.ts
packages/sdk/package.json
pnpm-lock.yaml
samples/todo/lib/hooks/list.ts
samples/todo/lib/hooks/space-user.ts
samples/todo/lib/hooks/space.ts
samples/todo/lib/hooks/todo.ts
samples/todo/lib/hooks/user.ts
samples/todo/package.json
samples/todo/pages/_app.tsx
tests/integration/test-run/package-lock.json
tests/integration/tests/e2e/prisma-methods.test.ts

- properly unmarshal superjson payload
- properly handle Prisma errors
- remove auxiliary fields on return
- fix mutation bugs

fix: various issues found while making tutorial

---

packages/schema/src/language-server/validator/zmodel-validator.ts
pnpm-lock.yaml

fix: vscode, skip validation when there's parsing/lexer error

---

packages/server/src/openapi/index.ts

fix(#300): handle invalid json in openapi query params gracefully

---

packages/plugins/openapi/src/generator.ts

feat: generate openapi doc with 3.1.0 version

---

packages/language/src/generated/ast.ts
packages/language/src/generated/grammar.ts
packages/language/src/zmodel.langium
packages/plugins/openapi/package.json
packages/plugins/openapi/src/generator.ts
packages/plugins/openapi/src/meta.ts
packages/plugins/openapi/src/schema.ts
packages/plugins/openapi/tests/openapi.test.ts
pnpm-lock.yaml
tests/integration/test-run/package-lock.json

- `securitySchemes` support
- `deprecated` support
- Custom tag description support

feat: improvements of openapi plugin

---

package.json
packages/language/package.json
packages/next/package.json
packages/plugins/openapi/package.json
packages/plugins/react/package.json
packages/plugins/trpc/package.json
packages/runtime/package.json
packages/schema/package.json
packages/schema/src/plugins/access-policy/policy-guard-generator.ts
packages/schema/src/plugins/model-meta/index.ts
packages/schema/src/plugins/zod/generator.ts
packages/schema/tests/schema/cal-com.zmodel
packages/sdk/package.json
packages/server/package.json
packages/testtools/package.json
packages/testtools/src/schema.ts
tests/integration/test-run/package-lock.json
tests/integration/tests/nextjs/test-project/postgres.zmodel
tests/integration/tests/nextjs/test-project/sqlite.zmodel
tests/integration/tests/schema/cal-com.zmodel
tests/integration/tests/schema/todo.zmodel
tests/integration/tests/trpc/test-project/todo.zmodel

- make core plugins compile generated ts files by default (#373)

merge dev to main

---

packages/language/src/generated/ast.ts
packages/language/src/generated/grammar.ts
packages/language/src/zmodel.langium
packages/schema/src/res/stdlib.zmodel
packages/schema/tests/schema/validation/attribute-validation.test.ts

- add missing params for `@@index`, `@@unique`, `@@id`
- allow more keywords as declaration names

fix: add missing attribute parameters and loosen keyword restrictions

---

packages/plugins/openapi/src/rest-generator.ts
packages/plugins/openapi/src/rpc-generator.ts
packages/plugins/openapi/tests/openapi-restful.test.ts
packages/plugins/openapi/tests/openapi-rpc.test.ts

fix: openapi plugin - make sure components are generated even model is marked ignored

---

packages/schema/src/cli/cli-util.ts
packages/testtools/src/schema.ts
tests/integration/tests/with-policy/multi-file.test.ts

- Set the $cotainer of all imported declarations to the main schema model
- add UT

fix: User model not found when using policy in the imported model

---

README.md
package.json
packages/language/package.json
packages/next/package.json
packages/plugins/openapi/package.json
packages/plugins/react/package.json
packages/plugins/swr/package.json
packages/plugins/tanstack-query/package.json
packages/plugins/trpc/package.json
packages/runtime/package.json
packages/runtime/src/enhancements/utils.ts
packages/schema/src/plugins/plugin-utils.ts
packages/sdk/package.json
packages/server/package.json
packages/testtools/package.json
tests/integration/test-run/package-lock.json

fix: avoid return loaded prisma if undefined (#461)

---

README.md

Doc:Update README.md

---

packages/runtime/package.json
packages/schema/package.json
pnpm-lock.yaml

fix: zod schema compilation errors in pnpm environment due to peer dependencies

---

package.json
packages/language/package.json
packages/plugins/openapi/package.json
packages/plugins/swr/package.json
packages/plugins/tanstack-query/package.json
packages/plugins/trpc/package.json
packages/runtime/package.json
packages/schema/package.json
packages/schema/src/plugins/model-meta/index.ts
packages/sdk/package.json
packages/server/package.json
packages/testtools/package.json
tests/integration/tests/regression/issues.test.ts

Should check if a `@relation` attribute really has `fields` argument to determine if it holds foreign key.

fix: incorrect relation owner analysis

---

packages/runtime/src/enhancements/policy/handler.ts
packages/runtime/src/enhancements/policy/policy-utils.ts
packages/schema/src/plugins/access-policy/expression-writer.ts
packages/schema/src/plugins/access-policy/policy-guard-generator.ts
packages/schema/tests/generator/expression-writer.test.ts
tests/integration/tests/enhancements/with-policy/deep-nested.test.ts
tests/integration/tests/enhancements/with-policy/nested-to-one.test.ts
tests/integration/tests/enhancements/with-policy/post-update.test.ts
tests/integration/tests/enhancements/with-policy/refactor.test.ts
tests/integration/tests/enhancements/with-policy/toplevel-operations.test.ts
tests/integration/tests/plugins/policy.test.ts

Use `{ AND: [] }` for `true` condition and `{ OR: [] }` for `false`

refactor: remove the usage of zenstack_guard field

---

package.json
packages/language/package.json
packages/plugins/openapi/package.json
packages/plugins/swr/package.json
packages/plugins/tanstack-query/package.json
packages/plugins/trpc/package.json
packages/runtime/package.json
packages/schema/package.json
packages/schema/src/plugins/access-policy/policy-guard-generator.ts
packages/sdk/package.json
packages/server/package.json
packages/testtools/package.json
pnpm-lock.yaml
tests/integration/tests/regression/issues.test.ts

When "create" rule involves foreign keys, don't generate input check guard.

fix: issue #627

---

packages/schema/src/plugins/zod/generator.ts
packages/testtools/package.json
packages/testtools/src/db.ts
packages/testtools/src/index.ts
packages/testtools/src/schema.ts
pnpm-lock.yaml
tests/integration/tests/enhancements/with-policy/field-comparison.test.ts
tests/integration/tests/enhancements/with-policy/postgres.test.ts
tests/integration/tests/enhancements/with-policy/refactor.test.ts
tests/integration/tests/regression/issues.test.ts
tests/integration/tests/schema/refactor-pg.zmodel
tests/integration/tests/schema/todo-pg.zmodel

fix: duplicated zod schema imported when there're multiple fields with an enum type

---

packages/schema/src/plugins/zod/generator.ts

Addresses https://github.com/zenstackhq/zenstack/issues/676.
I just edited this in Github after testing it out by hand, so I'm not 100% sure if it works.

fix: more precise Zod refinement types

---

packages/language/src/generated/ast.ts
packages/language/src/generated/grammar.ts
packages/language/src/zmodel.langium
packages/schema/package.json
packages/schema/src/plugins/prisma/prisma-builder.ts
packages/schema/src/plugins/prisma/schema-generator.ts
packages/schema/tests/generator/prisma-builder.test.ts
packages/schema/tests/generator/prisma-generator.test.ts
packages/schema/tests/schema/parser.test.ts
packages/sdk/src/utils.ts
pnpm-lock.yaml

fix: support postgres extensions

---

packages/schema/src/language-server/validator/expression-validator.ts
packages/schema/tests/schema/validation/attribute-validation.test.ts

fix: report validation error when binary expressions have arrays

---

packages/schema/src/res/stdlib.zmodel
pnpm-lock.yaml
tests/integration/tests/regression/issue-724.test.ts

fix: add missing MSSQL related stdlib declarations and parameters

---

packages/language/src/generated/grammar.ts
packages/language/src/zmodel.langium
packages/schema/tests/schema/abstract.test.ts

fix: allow models without field declarations

---

packages/plugins/trpc/src/generator.ts

fix: add eslint ignore to generated trpc helper source

---

packages/schema/src/plugins/plugin-utils.ts

fix: add missing exports for the generated .zenstack package

---

packages/plugins/swr/src/generator.ts
packages/plugins/tanstack-query/src/generator.ts

fix: lint issue in generated swr/tanstack hooks

---

package.json
packages/language/package.json
packages/plugins/openapi/package.json
packages/plugins/swr/package.json
packages/plugins/tanstack-query/package.json
packages/plugins/trpc/package.json
packages/runtime/package.json
packages/runtime/src/enhancements/policy/policy-utils.ts
packages/schema/package.json
packages/schema/src/plugins/zod/generator.ts
packages/schema/src/plugins/zod/utils/schema-gen.ts
packages/sdk/package.json
packages/server/package.json
packages/testtools/package.json
tests/integration/tests/enhancements/with-policy/field-validation.test.ts
tests/integration/tests/plugins/zod.test.ts
tests/integration/tests/schema/todo.zmodel

- Add PrismaCreate/PrismaUpdate schemas for internal use
- Make Create/Update schemas only include foreign keys but not relation

fix: clean up zod generation

---

packages/schema/src/plugins/access-policy/expression-writer.ts
tests/integration/tests/plugins/policy.test.ts

fix: Policy generator error for Auth() with multiple level member access

---

packages/schema/src/cli/cli-util.ts
packages/schema/src/plugins/prisma/schema-generator.ts
packages/schema/src/utils/pkg-utils.ts

fix 960: CLI crashes when package.json not found

---

packages/plugins/trpc/tests/projects/t3-trpc-v10/package.json
packages/runtime/package.json
packages/schema/package.json
pnpm-lock.yaml

chore: add prisma as peer dependency

---

packages/runtime/package.json
packages/schema/package.json
packages/sdk/package.json
pnpm-lock.yaml
tests/integration/test-run/package.json
tests/integration/tests/frameworks/nextjs/test-project/package.json
tests/integration/tests/frameworks/trpc/test-project/package.json

chore: update Prisma dependency to 5.15

---

packages/plugins/openapi/src/rpc-generator.ts
packages/plugins/openapi/tests/baseline/rpc-3.0.0.baseline.yaml
packages/plugins/openapi/tests/baseline/rpc-3.1.0.baseline.yaml
packages/plugins/openapi/tests/baseline/rpc-type-coverage-3.0.0.baseline.yaml
packages/plugins/openapi/tests/baseline/rpc-type-coverage-3.1.0.baseline.yaml

fix(openapi): wrong spec for "Meta" object for rpc-style generation

---

packages/schema/src/utils/ast-utils.ts

Just removing a debug logging statement left in the last release.
Thank you!

Cleanup debug log

---

packages/runtime/src/enhancements/node/delegate.ts
tests/integration/tests/enhancements/with-delegate/enhanced-client.test.ts
tests/integration/tests/enhancements/with-delegate/plugin-interaction.test.ts
tests/integration/tests/enhancements/with-delegate/utils.ts

fix(delegate): update `@updatedAt` fields inherited from delegate bases automatically

---

packages/runtime/src/enhancements/node/utils.ts
tests/regression/tests/issue-2106.test.ts

fix: error when logging prisma queries whose data contains BigInt

---

packages/schema/src/plugins/enhancer/enhance/index.ts
tests/regression/tests/issue-2175.test.ts

fix: regression with client extension typing
